apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
spec:
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: $IMAGE_NAME
          image: $COMPANY_NAME/$IMAGE_NAME
          command: ["python3", "/gtmhub_bot/gtmhub_bot.py"]
